production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/default
    #url: http://localhost:8983/solr/default
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/default
    #solr_home: solr

test:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING
    path: /solr/test
    solr_home: solr
    #http://hostname:8983/solr/